# Deploy resources using bicep
# I will create
  # Resource Group
  # Service Plan
  # App Service
  

trigger: none

variables:  
  webAppName: 'web-bicep'
  agentName: racknerdLinuxAgent
  location: $(Location)

stages:
  - stage: 
    displayName: Preview deployment resource
    jobs:
    - job:
      pool:
        name: LinuxAgent
        demands:
        - Agent.Name -equals $(agentName)

        steps:
        - task: AzureCLI@2
          displayName: Preview bicep
          inputs:
            azureSubscription: $(AzResourceGroup)
            scriptType: 'bash'
            scriptLocation: inlineScript
            inlineScript: |
              az group create --name $(Build.BuildNumber) \
              az deployment group what-if --resource-group $(resourceGroupName) --location $(location)\
              --template-file deployment/template.bicep
              --parameters webAppName=$(webAppName) appServicePlan=$(appServicePlan)

  




