# Deploy resources using bicep
# I will create
  # Resource Group
  # Service Plan
  # App Service
  

trigger: none

variables:  
  webAppName: 'web-bicep'
  agentName: racknerdLinuxAgent
  serviceConnectionName: 'MyAzSubscription'  

pool:
  name: LinuxAgent
  demands:
  - Agent.Name -equals $(agentName)

steps:
- task: AzureCLI@2
  displayName: Preview bicep
  inputs:
    azureSubscription: $(serviceConnectionName)
    scriptType: 'bash'
    scriptLocation: inlineScript
    inlineScript: |
      az group create --name $(ResourceGroupName) --location $(Location)
      az deployment group create --resource-group ab-nodejsapp-stg-rg --name $(Build.BuildNumber) --template-file template.bicep --parameters webAppName=$(webAppName) appServicePlan=$(appServicePlan) location=$(Location)

