# Deploy resources using bicep
# I will create
  # Resource Group
  # Service Plan
  # App Service
  

trigger: none

variables:  
  webAppName: 'web-bicep'
  agentName: racknerdLinuxAgent

pool:
  name: LinuxAgent
  demands:
  - Agent.Name -equals $(agentName)

steps:
- task: AzureCLI@2
  displayName: Preview bicep
  inputs:
    azureSubscription: 'MyAzSubscription'
    scriptType: 'bash'
    scriptLocation: inlineScript
    inlineScript: |
      az group create --name $(Build.BuildNumber) \
      az deployment group what-if --resource-group $(ResourceGroupName) --location $(Location)\
      --template-file deployment/template.bicep
      --parameters webAppName=$(webAppName) appServicePlan=$(appServicePlan)

  




