# Run the bash script to tear down un used resources in azure
# Run Bash

trigger: none

variables:
  agentName: racknerdAgentLinux
  serviceConnectionName: MyAzSubscription

pool:
  name: LinuxAgentPool
  demands:
  - Agent.Name -equals $(agentName)


steps:
- task: Bash@3
  displayName: Destroy resources
  inputs:
    targetType: filePath
    filePath: $(System.DefaultWorkingDirectory)/pipelines/tear-down-resources.yml
    arguments: $(ResourceGroupName) $(webAppName)